import Cottage from './Cottage.jsx';
import {useGameAudio} from './audio.js';
import React,{useEffect,useRef,useState} from 'react';
import {flowers,questions,themes,levels,vaseColors,wallColors,shapeNames,decorNames,patternNames,windowNames,itemNames,careQuestions,careActions,careMessages,arrangementDefaults,flowerIds,bouquetId,normalizeSave,getLetter,localDay} from './game-data.js';
import {PixelTitle,Icon,Room,FlowerIcon,VaseIcon,SideItem} from './pixel-art.jsx';

const STORAGE='my-bouquet-excel-v2';
// Explicit local fresh-start link; removes only this game's saved progress.
if(typeof window!=='undefined' && new URLSearchParams(window.location.search).get('new-player')==='1'){
 try{const previous=localStorage.getItem(STORAGE);if(previous)localStorage.setItem(STORAGE+'-before-reset',previous);localStorage.removeItem(STORAGE);const url=new URL(window.location.href);url.searchParams.delete('new-player');window.history.replaceState(null,'',url.pathname+url.search+url.hash)}catch{}
}

function readSave(){try{return normalizeSave(JSON.parse(localStorage.getItem(STORAGE)))}catch{return normalizeSave(null)}}
function Btn({children,icon,primary=false,className='',...props}){return <button className={`pixel-button ${primary?'primary':''} ${className}`} {...props}>{icon&&<Icon name={icon}/>}<span>{children}</span></button>}
function SectionHeading({label,children}){return <div className="section-heading"><span>{label}</span><h2>{children}</h2></div>}

 function Choices({save,customize,label,field,items,type='text'}){return <fieldset className="custom-group"><legend>{label}</legend><div className={`choice-grid ${type==='color'?'color-grid':type==='vase'?'vase-grid':''}`}>{items.map((item,i)=><button key={i} className={`choice-tile ${save.custom[field]===i?'chosen':''}`} aria-label={type==='color'?`${label} ${i+1}`:item} aria-pressed={save.custom[field]===i} onClick={()=>customize(field,i)}>{type==='color'?<span className="swatch" style={{backgroundColor:item}}>{save.custom[field]===i?'✓':''}</span>:type==='vase'?<><VaseIcon custom={{...save.custom,shape:i}}/><span>{item}</span></>:type==='item'?<><svg viewBox="-5 -3 38 35" className="item-preview" aria-hidden="true" shapeRendering="crispEdges"><SideItem kind={i}/></svg><span>{item}</span></>:type==='window'?<><span className={`window-preview window-${i}`}/><span>{item}</span></>:type==='pattern'?<><span className={`pattern-preview pattern-${i}`}/><span>{item}</span></>:<><Icon name={['heart','flower','star'][i%3]}/><span>{item}</span></>}</button>)}</div></fieldset>}

export default function App(){
 const [save,setSave]=useState(readSave),[screen,setScreen]=useState(()=>{const s=readSave();return s.complete?'home':s.answers.length===5?'arrange':s.answers.length?'reflect':'intro'});
 const [choice,setChoice]=useState(null),[editTab,setEditTab]=useState('vase'),[selected,setSelected]=useState(0),[opened,setOpened]=useState(false),[opening,setOpening]=useState(false),[letter,setLetter]=useState(null),[letterError,setLetterError]=useState(''),[retry,setRetry]=useState(0),[fx,setFx]=useState(''),[toast,setToast]=useState(''),[storageError,setStorageError]=useState(false),[bookFilter,setBookFilter]=useState('all'),[bookFlower,setBookFlower]=useState(null),[returnScreen,setReturnScreen]=useState('home');
 const [care,setCare]=useState(()=>{const s=readSave();return s.careDate===localDay()?s.care:[null,null,null]});
 const music=useGameAudio(save.sound);
 const [notice,setNotice]=useState(false);
 const [burst,setBurst]=useState(null);const burstTimer=useRef(null);
 useEffect(()=>()=>clearTimeout(burstTimer.current),[]);
 const [day,setDay]=useState(localDay);
 useEffect(()=>{const id=setInterval(()=>setDay(localDay()),30000);return()=>clearInterval(id)},[]);
 const fxTimer=useRef(null),letterTimer=useRef(null),toastTimer=useRef(null),heading=useRef(null),initial=useRef(true);
 const update=patch=>setSave(s=>({...s,...patch}));
 const full=save.answers.length===5,step=Math.min(save.answers.length,4),activeStep=screen==='reflect'?0:screen==='arrange'?1:screen==='custom'?(editTab==='vase'?2:3):screen==='letter'?4:-1;
 useEffect(()=>{try{localStorage.setItem(STORAGE,JSON.stringify(save));setStorageError(false)}catch{setStorageError(true)}},[save]);
 useEffect(()=>{if(initial.current){initial.current=false;return}heading.current?.focus({preventScroll:true})},[screen]);
 useEffect(()=>()=>{clearTimeout(fxTimer.current);clearTimeout(letterTimer.current);clearTimeout(toastTimer.current);},[]);
 useEffect(()=>{if(screen!=='letter'||!full)return;const controller=new AbortController();setLetter(null);setLetterError('');getLetter(save.answers,controller.signal).then(value=>{setLetter(value);music.play('arrival')}).catch(e=>{if(e.name!=='AbortError')setLetterError(e.message)});return()=>controller.abort()},[screen,save.answers,retry]);
 function sound(kind='tap',force=false){music.play(kind,force)}
 function effect(type){setFx(type);clearTimeout(fxTimer.current);fxTimer.current=setTimeout(()=>setFx(''),1800)}
 function notify(message){setToast(message);clearTimeout(toastTimer.current);toastTimer.current=setTimeout(()=>setToast(''),3200)}
 function go(next){sound();setScreen(next);setBookFlower(null);setNotice(false)}
 function start(){update({answers:[],complete:false,positions:arrangementDefaults.map(p=>({...p}))});setChoice(null);setOpened(false);setOpening(false);go('reflect')}
 function collect(){if(choice===null)return;const id=step*5+choice,next=[...save.answers,choice];update({answers:next,unlocked:[...new Set([...save.unlocked,id])],complete:false});setChoice(null);sound('bloom');effect('sparkle');if(next.length===5)setScreen('arrange')}
 function customize(k,v){update({custom:{...save.custom,[k]:v}});sound()}
 function openBook(){if(screen!=='journal')setReturnScreen(screen);go('journal')}
 function returnHome(){go(save.complete?'home':full?'arrange':save.answers.length?'reflect':'intro')}
 function arrangeDone(){if(save.hasVase){setOpened(false);go('letter')}else{setEditTab('vase');go('custom')}}
 function finishCustom(){update({hasVase:true});if(save.complete){notify('Góc hoa đã được lưu lại rồi.');go('home')}else{setOpened(false);go('letter')}}
 function openEnvelope(){if(!letter||opening)return;sound('letter');setOpening(true);letterTimer.current=setTimeout(()=>{setOpened(true);setOpening(false);update({complete:true,hasVase:true})},720)}
 function moveFlower(i,pos){setSave(s=>({...s,positions:s.positions.map((p,j)=>j===i?pos:p)}))}
 function nudge(dx,dy){const p=save.positions[selected];moveFlower(selected,{x:Math.max(112,Math.min(199,p.x+dx)),y:Math.max(43,Math.min(102,p.y+dy))});sound()}
 function careAnswer(i,v){const next=care.map((a,j)=>j===i?v:a);setCare(next);effect(['water','sun','scissors'][i]);sound('bloom');if(next.every(a=>a!==null))update({careDate:localDay(),care:next})}
 const titles={intro:'Một góc nhỏ dành cho bạn',home:'Mừng bạn trở về',reflect:'Lắng nghe mình một chút',arrange:'Cắm hoa theo cách của bạn',custom:'Trang trí góc hoa',letter:'Một lá thư gửi riêng bạn',care:'Chăm hoa, chăm mình',journal:'Sổ hoa của bạn'};
 const stageNames=['Lắng nghe','Cắm hoa','Chiếc bình','Góc nhỏ','Lá thư'];
 const bookList=flowers.filter(f=>bookFilter==='all'||(bookFilter==='unlocked'?save.unlocked.includes(f.id):Math.floor(f.id/5)===Number(bookFilter)));

 return <div className="world" onPointerOver={e=>{const button=e.target.closest('button:not(:disabled)');if(e.pointerType==='mouse'&&button&&!button.contains(e.relatedTarget))music.play('hover')}} onClickCapture={e=>{if(e.target.closest('button:not(:disabled)')){music.wake();music.play('tap');const r=e.target.closest('button').getBoundingClientRect();setBurst({x:e.detail?e.clientX:r.left+r.width/2,y:e.detail?e.clientY:r.top+r.height/2,id:performance.now()});clearTimeout(burstTimer.current);burstTimer.current=setTimeout(()=>setBurst(null),650)}}}><div className="ambient-flower ambient-one"><FlowerIcon id={10}/></div><div className="ambient-flower ambient-two"><FlowerIcon id={1}/></div><div className="ambient-star star-one">✦</div><div className="ambient-star star-two">✦</div>
 <div className="game-shell"><header className="game-header"><button className="brand" onClick={returnHome} aria-label="My Bouquet — về góc hoa"><span className="brand-flower brand-flower-left" aria-hidden="true"><FlowerIcon id={10}/></span><span className="brand-wordmark"><PixelTitle/><span className="brand-tagline">A LITTLE KINDNESS GROWS HERE</span></span><span className="brand-flower brand-flower-right" aria-hidden="true"><FlowerIcon id={1}/></span><i className="brand-star star-a" aria-hidden="true">✦</i><i className="brand-star star-b" aria-hidden="true">✧</i></button><div className="header-controls" hidden={screen==='intro'}><div className="notification-wrap"><button className="care-bell" aria-label="Thông báo chăm hoa" aria-expanded={notice} onClick={()=>setNotice(v=>!v)}><Icon name="bell" size={26}/>{save.complete&&save.careDate!==day&&<span className="notification-dot"/>}</button>{notice&&<div className="notification-card" role="status"><strong>{!save.complete?'Góc hoa đang chờ bạn':save.careDate===day?'Hoa đã được chăm hôm nay':'Hoa nhớ bạn rồi!'}</strong><p>{!save.complete?'Tạo bó hoa đầu tiên để bắt đầu chăm hoa mỗi ngày.':save.careDate===day?'Mai mình lại ghé thăm nhé.':'Một chút nước, chút nắng và một lần tỉa lá nhé?'}</p>{save.complete&&<Btn primary onClick={()=>{setCare(save.careDate===day?save.care:[null,null,null]);go('care')}}>Ghé chăm hoa</Btn>}</div>}</div><Btn icon="book" onClick={openBook} aria-current={screen==='journal'?'page':undefined}>Sổ hoa <b>{save.unlocked.length}/25</b></Btn><button className={`sound-button ${save.sound?'sound-on':''}`} aria-label={save.sound?'Tắt âm thanh':'Bật âm thanh'} aria-pressed={save.sound} onClick={()=>{update({sound:!save.sound});if(!save.sound)sound('bloom',true)}}><Icon name="music"/>{!save.sound&&<span className="mute-line"/>}</button></div></header>
 <main className={`game-window screen-${screen}`}><div className="window-titlebar"><span><Icon name="flower" size={14}/> MY BOUQUET</span><span className="window-dots" aria-hidden="true">◇ &nbsp; □ &nbsp; ×</span></div><div className="game-topline"><div><p className="eyebrow">{screen==='journal'?'FLOWER JOURNAL':screen==='care'?'A LITTLE CARE':screen==='home'?'HOME, SWEET HOME':'YOUR FEELINGS CAN BLOOM HERE'}</p><h1 ref={heading} tabIndex={-1}>{titles[screen]}</h1></div></div>
 {activeStep>=0&&<ol className="journey" aria-label="Hành trình tạo bó hoa">{stageNames.map((name,i)=><li className={`${activeStep===i?'current':''} ${activeStep>i?'done':''}`} key={name} aria-current={activeStep===i?'step':undefined}><span>{activeStep>i?'✓':i+1}</span>{name}</li>)}</ol>}
 {screen==='journal'?<section className="journal-layout"><div className="journal-toolbar"><p>Mỗi cảm xúc đều có một bông hoa của riêng mình.</p><Btn onClick={()=>go(returnScreen)} icon="home">Quay lại</Btn></div><div className="book-filters" aria-label="Lọc sổ hoa">{[['all','Tất cả'],['unlocked','Đã tìm thấy'],...themes.map((t,i)=>[String(i),t])].map(([value,label])=><button key={value} aria-pressed={bookFilter===value} className={bookFilter===value?'active':''} onClick={()=>{setBookFilter(value);sound()}}>{label}</button>)}</div><div className="journal-grid">{bookList.map(f=>{const unlocked=save.unlocked.includes(f.id);return <button className={`journal-card ${unlocked?'unlocked':''}`} key={f.id} onClick={()=>{setBookFlower(f.id);sound()}} aria-label={unlocked?`Xem ${f.name}`:`Hoa ${f.id+1} chưa mở khóa`}><span className="flower-number">{String(f.id+1).padStart(2,'0')}</span><FlowerIcon id={f.id} locked={!unlocked}/><strong>{unlocked?f.name:'Chưa hé nở'}</strong><small>{unlocked?f.english:'Một điều dịu dàng đang đợi'}</small>{unlocked?<span className="unlocked-label">Đã tìm thấy</span>:<Icon name="lock" size={13}/>}</button>})}</div>{!bookList.length&&<div className="empty-book"><Icon name="flower" size={32}/><p>Bông hoa đầu tiên đang đợi bạn ở hành trình lắng nghe.</p><Btn primary onClick={returnHome}>Về góc hoa</Btn></div>}{bookFlower!==null&&<section className="flower-detail" aria-live="polite"><FlowerIcon id={bookFlower} locked={!save.unlocked.includes(bookFlower)}/><div><h2>{save.unlocked.includes(bookFlower)?flowers[bookFlower].name:'Một bông hoa chưa hé nở'}</h2><p>{save.unlocked.includes(bookFlower)?flowers[bookFlower].meaning:'Hãy tiếp tục lắng nghe cảm xúc thật của mình. Ý nghĩa của bông hoa sẽ xuất hiện khi bạn tìm thấy nó.'}</p>{save.unlocked.includes(bookFlower)&&<small>{flowers[bookFlower].english} · {themes[Math.floor(bookFlower/5)]}</small>}</div><button className="close-detail" onClick={()=>setBookFlower(null)} aria-label="Đóng chi tiết hoa">×</button></section>}</section>:<div className="play-layout">
 <section className="room-panel" aria-label="Góc hoa của bạn"><div className="room-top"><span><Icon name="sun" size={14}/> {screen==='care'?'Một ngày để dịu dàng':screen==='arrange'?'Bàn cắm hoa của bạn':'Một góc bình yên'}</span><span>✦ &nbsp; ✦ &nbsp; ✦</span></div>{screen==='intro'?<Cottage/>:<Room showVase={save.hasVase||['custom','letter','home','care'].includes(screen)} answers={save.answers} custom={save.custom} positions={save.positions} preview={false} editable={screen==='arrange'} selected={selected} onSelect={setSelected} onMove={moveFlower} fx={fx} onBouquetTap={()=>{effect('sparkle');sound('bloom')}}/>}<div className="room-caption"><Icon name="heart" size={13}/>{screen==='arrange'?'Kéo bông hoa để sắp xếp. Hoặc chọn hoa rồi dùng nút mũi tên.':fx?{water:'Một chút nước mát cho hoa.',sun:'Nắng ghé vào góc nhỏ rồi.',scissors:'Bớt một chiếc lá, thêm một khoảng thở.',sparkle:'Bó hoa khẽ chào bạn.'}[fx]:'Không cần vội. Hoa cũng nở theo nhịp riêng.'}</div>
 {screen!=='intro'&&<div className="flower-tray" aria-label="Năm bông hoa của bạn">{Array.from({length:5},(_,i)=>{const id=save.answers[i]===undefined?null:i*5+save.answers[i];return <button disabled={id===null||screen!=='arrange'} className={`tray-cell ${id!==null?'has-flower':''} ${screen==='arrange'&&selected===i?'selected':''}`} key={i} onClick={()=>{setSelected(i);sound()}} aria-label={id===null?`Chỗ hoa ${i+1}`:`Chọn ${flowers[id].name}`} aria-pressed={screen==='arrange'?selected===i:undefined}>{id===null?<span className="empty-slot">?</span>:<FlowerIcon id={id} stem={false}/>}<small>{id===null?`Hoa ${i+1}`:flowers[id].name}</small></button>})}</div>}{full&&screen!=='intro'&&<div className="bouquet-label">MY BOUQUET <span>No. {String(bouquetId(save.answers)).padStart(4,'0')}</span></div>}</section>
 <section className="interaction-panel">
 {screen==='intro'&&<div className="welcome-panel"><span className="tiny-label"><Icon name="heart" size={14}/> MỘT MÓN QUÀ CHO CHÍNH MÌNH</span><h2>Một bó hoa<br/>dành riêng cho bạn.</h2><div className="welcome-path"><span><Icon name="heart"/>Lắng nghe</span><i>···</i><span><Icon name="flower"/>Cắm hoa</span><i>···</i><span><Icon name="letter"/>Nhận thư</span></div><Btn primary className="wide" onClick={start}>Bắt đầu</Btn><small className="gentle-note">Không có đúng hay sai. Chỉ có bạn, ngay lúc này.</small></div>}
 {screen==='reflect'&&<><div className="question-heading"><span className="tiny-label">{themes[step]}</span><span className="question-count">{step+1} / 5</span></div><div className="heart-progress">{Array.from({length:5},(_,i)=><Icon key={i} name="heart" size={17} className={i<=step?'lit':''}/>)}</div><h2 className="reflection-question" key={step}>{questions[step]}</h2><p className="selection-hint">Điều nào gần với bạn nhất hôm nay?</p><div className="answer-choices" role="radiogroup" aria-label="Mức độ giống bạn">{levels.map((label,i)=><label className={`answer-option ${choice===i?'chosen':''}`} key={i}><input type="radio" name="answer" checked={choice===i} onChange={()=>{setChoice(i);sound()}}/><span className="level-number">{i+1}</span><span>{label}</span><Icon name="heart" size={14}/></label>)}</div><div className={`flower-reveal ${choice!==null?'revealed':''}`} aria-live="polite">{choice!==null?<><FlowerIcon id={step*5+choice}/><div><small>BÔNG HOA ĐÃ TÌM THẤY BẠN</small><strong>{flowers[step*5+choice].name}</strong><p>{flowers[step*5+choice].meaning}</p></div></>:<><Icon name="star"/><p>Một bông hoa đang chờ hé nở…</p></>}</div><Btn primary className="wide" icon="flower" disabled={choice===null} onClick={collect}>{step===4?'Nhận hoa & cùng cắm bình':'Nhận bông hoa này'}</Btn>{step>0&&<button className="text-button" onClick={()=>{const last=save.answers.at(-1);update({answers:save.answers.slice(0,-1)});setChoice(last);sound()}}>← Quay lại câu trước</button>}</>}
 {screen==='arrange'&&<><SectionHeading label="FIVE FEELINGS, ONE BOUQUET">Hoa đã ở đây đủ rồi.</SectionHeading><p>Kéo hoa để sắp xếp theo ý bạn.</p><div className="selected-flower"><FlowerIcon id={flowerIds(save.answers)[selected]}/><div><small>ĐANG CHỌN</small><h3>{flowers[flowerIds(save.answers)[selected]].name}</h3><p>{flowers[flowerIds(save.answers)[selected]].meaning}</p></div></div><div className="arrange-pad" aria-label="Di chuyển bông hoa đã chọn"><button onClick={()=>nudge(0,-3)} aria-label="Nâng hoa lên">↑</button><div><button onClick={()=>nudge(-3,0)} aria-label="Dịch hoa sang trái">←</button><span><Icon name="flower"/></span><button onClick={()=>nudge(3,0)} aria-label="Dịch hoa sang phải">→</button></div><button onClick={()=>nudge(0,3)} aria-label="Hạ hoa xuống">↓</button></div><button className="text-button" onClick={()=>{update({positions:arrangementDefaults.map(p=>({...p}))});sound()}}>Sắp xếp lại từ đầu</button><Btn primary className="wide" icon="arrow" onClick={arrangeDone}>{save.hasVase?'Bó hoa xong rồi · Nhận thư':'Chọn một chiếc bình'}</Btn></>}
 {screen==='custom'&&<><SectionHeading label="MAKE YOURSELF AT HOME">{editTab==='vase'?'Một ngôi nhà cho hoa.':'Thêm chút riêng mình.'}</SectionHeading><div className="custom-tabs"><button aria-pressed={editTab==='vase'} className={editTab==='vase'?'active':''} onClick={()=>{setEditTab('vase');sound()}}><Icon name="flower"/> Chiếc bình</button><button aria-pressed={editTab==='corner'} className={editTab==='corner'?'active':''} onClick={()=>{setEditTab('corner');sound()}}><Icon name="home"/> Góc đặt hoa</button></div><div className="custom-scroller">{editTab==='vase'?<><Choices save={save} customize={customize} label="Dáng bình" field="shape" items={shapeNames} type="vase"/><Choices save={save} customize={customize} label="Màu bình" field="color" items={vaseColors} type="color"/><Choices save={save} customize={customize} label="Trang trí bình" field="decor" items={decorNames}/></>:<><Choices save={save} customize={customize} label="Họa tiết tường" field="pattern" items={patternNames} type="pattern"/><Choices save={save} customize={customize} label="Màu tường" field="wall" items={wallColors} type="color"/><Choices save={save} customize={customize} label="Khung cửa sổ" field="window" items={windowNames} type="window"/><Choices save={save} customize={customize} label="Một món đồ nhỏ" field="item" items={itemNames} type="item"/></>}</div><Btn primary className="wide" icon={editTab==='vase'?'arrow':save.complete?'heart':'letter'} onClick={editTab==='vase'?()=>{setEditTab('corner');sound()}:finishCustom}>{editTab==='vase'?'Tiếp theo · Góc đặt hoa':save.complete?'Lưu góc hoa':'Góc nhỏ xong rồi · Nhận thư'}</Btn></>}
 {screen==='letter'&&<><SectionHeading label="A LETTER, JUST FOR YOU">{opened?'Gửi bạn, với thật nhiều thương.':'Có một lá thư vừa đến.'}</SectionHeading>{!opened?<div className="envelope-panel"><p>Chạm để mở lời nhắn của bạn.</p><button className={`pixel-envelope ${opening?'opening':''}`} aria-label="Mở lá thư" disabled={!letter||opening} onClick={openEnvelope}><span className="envelope-paper"/><span className="envelope-body"/><span className="envelope-flap"/><span className="envelope-seal"><Icon name="heart" size={26}/></span><span className="envelope-spark">✦</span></button>{letterError?<div role="alert"><p>{letterError}</p><Btn onClick={()=>setRetry(v=>v+1)}>Thử lấy thư lại</Btn></div>:<p className="tap-invitation" aria-live="polite">{letter?'CHẠM VÀO PHONG THƯ ĐỂ MỞ':'Đang mang thư đến…'}</p>}</div>:<><article className="letter-paper"><div className="letter-corner"><Icon name="flower" size={23}/></div><div className="letter-content">{letter?.text}</div><div className="letter-signoff"><Icon name="heart" size={14}/> MY BOUQUET</div></article><Btn primary className="wide" icon="home" onClick={()=>go('home')}>Cất thư & về góc hoa</Btn></>}</>}
 {screen==='home'&&<><SectionHeading label="YOUR LITTLE SANCTUARY">Hoa vẫn ở đây,<br/>đợi bạn một chút.</SectionHeading><div className="daily-note"><Icon name={save.careDate===day?'heart':['water','sun','scissors'][new Date().getDate()%3]} size={27}/><div><strong>{save.careDate===day?'Hôm nay hoa đã được chăm rồi.':['Hoa đang mong một chút nước mát.','Góc hoa đang đợi chút nắng ấm.','Vài chiếc lá đang đợi được chăm.'][new Date().getDate()%3]}</strong><p>{save.careDate===day?'Cảm ơn bạn đã dành chút dịu dàng cho góc nhỏ này.':'Mình ghé thăm hoa, rồi hỏi han chính mình một chút nhé.'}</p></div></div><Btn primary className="wide" icon="water" onClick={()=>{setCare(save.careDate===day?save.care:[null,null,null]);go('care')}}>Chăm hoa hôm nay</Btn><div className="home-menu"><Btn icon="brush" onClick={()=>{setEditTab('vase');go('custom')}}>Trang trí góc hoa</Btn><Btn icon="letter" onClick={()=>{setOpened(false);go('letter')}}>Đọc lại lá thư</Btn><Btn icon="flower" onClick={start}>Tạo bó hoa mới</Btn></div></>}
 {screen==='care'&&<><SectionHeading label="LITTLE THINGS MATTER">Mình chăm nhau<br/>từng chút một.</SectionHeading><p className="care-intro">Dù câu trả lời là gì, hoa vẫn được chăm. Bạn cũng xứng đáng được dịu dàng như thế.</p><div className="care-cards">{careQuestions.map((q,i)=><section className={`care-card ${care[i]!==null?'cared':''}`} key={q}><div className="care-title"><Icon name={['water','sun','scissors'][i]}/><small>0{i+1} · {careActions[i]}</small>{care[i]!==null&&<span>✓</span>}</div><h3>{q}</h3><div className="yes-no">{[true,false].map(v=><button key={String(v)} aria-pressed={care[i]===v} className={care[i]===v?'chosen':''} onClick={()=>careAnswer(i,v)}>{v?'Có':'Chưa / Không'}</button>)}</div>{care[i]!==null&&<p className="care-response" role="status">{careMessages[i][care[i]?0:1]}</p>}</section>)}</div><Btn primary className="wide" icon="home" disabled={care.some(v=>v===null)} onClick={()=>go('home')}>Hoa được chăm rồi · Về góc nhỏ</Btn><button className="text-button" onClick={()=>go('home')}>Để mình quay lại sau</button></>}
 </section></div>}
 <div className="game-bottom"><span><Icon name="heart" size={12}/> Không có cảm xúc nào là sai.</span><span>{screen==='journal'?`${save.unlocked.length} / 25 bông hoa đã tìm thấy`:'Made of pixels & a little tenderness'}</span></div></main><footer className="page-footer"><span>MY BOUQUET · một chút dịu dàng, mỗi ngày.</span><span>Chỉ lưu trên trình duyệt của bạn.</span></footer><p className="quiet-disclaimer">Một trò chơi tự suy ngẫm, không phải bài đánh giá sức khỏe tâm lý.</p></div>
 {burst&&<div className="click-burst" key={burst.id} style={{left:burst.x,top:burst.y}} aria-hidden="true">{Array.from({length:7},(_,i)=><i key={i} style={{'--dx':`${Math.cos(i*Math.PI*2/7)*37}px`,'--dy':`${Math.sin(i*Math.PI*2/7)*37}px`,'--turn':`${i*45}deg`}}/> )}</div>}
 <div className="garden-motes" aria-hidden="true">{Array.from({length:9},(_,i)=><i key={i} style={{left:`${6+i*11}%`,animationDelay:`${-i*1.7}s`,animationDuration:`${12+i%4*2}s`}}/>)}</div>
 {toast&&<div className="toast" role="status"><Icon name="heart"/>{toast}</div>}{storageError&&<div className="storage-warning" role="status">Trình duyệt chưa lưu được tiến trình. Bạn vẫn có thể chơi trong phiên này.</div>}</div>
}
